This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file /Users/felix/Documents/Repositories/TUM/ABSA-Transformer/Thesis/.texpadtmp/main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/felix/Documents/Repositories/TUM/ABSA-Transformer/Thesis/.texpadtmp/main.acn....done (42 entries accepted, 0 rejected).
Sorting entries....done (224 comparisons).
Generating output file /Users/felix/Documents/Repositories/TUM/ABSA-Transformer/Thesis/.texpadtmp/main.acr....done (72 lines written, 0 warnings).
Output written in /Users/felix/Documents/Repositories/TUM/ABSA-Transformer/Thesis/.texpadtmp/main.acr.
Transcript written in /Users/felix/Documents/Repositories/TUM/ABSA-Transformer/Thesis/.texpadtmp/main.alg.
