
# General 
TEST_MODE = True
INCLUDE_ASSERTS = True

# Attention
DEFAULT_NUMBER_OF_ATTENTION_HEADS = 8
DEFAULT_DIMENSION_OF_KEYQUERY_WEIGHTS = 64
DEFAULT_DIMENSION_OF_VALUE_WEIGHTS = 64
DEFAULT_MODEL_DROPOUT = 0.1

# Point Wise FC
DEFAULT_DIMENSION_OF_PWFC_HIDDEN_LAYER = 2048

# General Model Parameters
DEFAULT_DIMENSION_OF_MODEL = DEFAULT_NUMBER_OF_ATTENTION_HEADS * DEFAULT_DIMENSION_OF_KEYQUERY_WEIGHTS # 512
DEFAULT_EMBEDDING_SIZE = 512

# Encoder Parameters
DEFAULT_ENCODER_BLOCKS = 6
DEFAULT_LAYER_SIZE = 512

